# version: '3'
# services:
#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: 'password'
#     ports:
#       - "4306:3306"

#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/app_name
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db

version: '3'

services:
  web:
    container_name: myapp_web_prod
    build: .
    environment:
      RAILS_ENV: production
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
      - ./public:/myapp/public
      - ./tmp:/myapp/tmp
      - ./log:/myapp/log
    ports:
      - 3000:3000

  nginx:
    container_name: myapp_nginx_prod
    build: containers/nginx
    volumes:
      - ./public:/myapp/public
      - ./tmp:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - web